# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_bid', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_bid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('end_date', models.DateTimeField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('when_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreage', models.FloatField()),
                ('name', models.TextField()),
                ('pin', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gis_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tract',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tracts', to='timberlistapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='tract',
            name='owner_history',
            field=models.ManyToManyField(related_name='owned_tracts_history', to='timberlistapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='listing',
            name='tract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timberlistapp.Tract'),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timberlistapp.Listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timberlistapp.UserProfile'),
        ),
    ]
