# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0002_auto_20160320_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='who_added',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='tract',
            old_name='current_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='owner',
        ),
    ]
