# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 00:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0004_auto_20160326_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.TextField(max_length=512)),
                ('address2', models.TextField(blank=True, max_length=512)),
                ('city', models.TextField(max_length=512)),
                ('county', models.TextField(max_length=256)),
                ('state', models.TextField(max_length=2)),
                ('country', models.TextField(max_length=2)),
                ('zipcode', models.TextField(max_length=10)),
                ('lat_long', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cell',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fax',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='timberlistapp.Address'),
        ),
    ]
