# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0005_auto_20160330_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat_long',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
