# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0006_auto_20160330_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.TextField(blank=True),
        ),
    ]
