# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0007_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile',
            new_name='description',
        ),
    ]
