# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0009_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
