# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 21:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0011_auto_20160401_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tract',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tract',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tract',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tract',
            name='lat_long',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tract',
            name='acreage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tract',
            name='gis_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tract',
            name='pin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
