# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0012_auto_20160406_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='timberlistapp.Listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timberlistapp.UserProfile')),
            ],
        ),
    ]
