# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0013_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='minimum_bid',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='timberlistapp.UserProfile'),
        ),
    ]
