# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timberlistapp', '0015_auto_20160711_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
